return {
  -- {
  --   "neovim/nvim-lspconfig",
  --   ---@class PluginLspOpts
  --   opts = {
  --     ---@type lspconfig.options
  --     servers = {
  --       -- disable solargraph from auto running when you open ruby files
  --       solargraph = {
  --         autostart = false,
  --       },
  --       -- ruby_lsp will be automatically installed with mason and loaded with lspconfig
  --       ruby_lsp = {
  --         -- mason = false,
  --         -- cmd = { os.getenv("HOME") .. "/.asdf/shims/ruby-lsp" },
  --         -- cmd = { "bundle", "exec", "ruby-lsp" },
  --
  --         init_options = {
  --           enabledFeatures = {
  --             "codeActions",
  --             "codeLens",
  --             "completion",
  --             "definition",
  --             "documentHighlights",
  --             "documentSymbols",
  --             "foldingRanges",
  --             "hover",
  --             "inlayHint",
  --             "selectionRanges",
  --             "semanticHighlighting",
  --             "workspaceSymbol",
  --           },
  --         },
  --       },
  --     },
  --   },
  -- },
}
