[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.7
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 18

[[hints.enabled]]
command = "open"
hyperlinks = true
mouse.enabled = true
mouse.mods = "Super"
post_processing = true
persist = false
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘]+"

[keyboard]
bindings = [
  #Skip word left
  { key = "Left", mods = "Alt", chars = "\u001BB" },
  # Skip word right
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  # Home
  { key = "Left", mods = "Command", chars = "\u001bOH" },
  # End
  { key = "Right", mods = "Command", chars = "\u001bOF" },
  # Delete line
  { key = "Back", mods = "Command", chars = "\u0015" },
  # Delete word
  { key = "Back", mods = "Alt", chars = "\u001b\u007f" },
  # Copy to Clipboard
  { key = "c", mods = "Command", action = "Copy" },
  { key = "Comma", mods = "Command", command = { program = "sh", args = [
    "-c",
    "nvim ~/.config/alacritty/alacritty.yml",
  ] } },

  # tab navigation
  { key = "T", mods = "Control", action = "CreateNewTab" },
] # - { key: N,         mods: Command,      action: SpawnNewInstance       }
# - { key: Space,     mods: Alt,          chars: " "                     }
# - { key: Back, mods: Super, chars: "\x15" } # delete word/line
# - { key: Left,     mods: Alt,     chars: "\x1bb"                       } # one word left
# - { key: Right,    mods: Alt,     chars: "\x1bf"                       } # one word right
# - { key: Left,     mods: Command, chars: "\x1bOH",   mode: AppCursor   } # Home
# - { key: Right,    mods: Command, chars: "\x1bOF",   mode: AppCursor   } # End
# - { key: Comma,     mods: Command,      command:
#       {program: "sh", args: ["-c","open ~/.config/alacritty/alacritty.yml"]}     }
