"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[➜](bold green)'

[package]
disabled = true

[git_branch]
disabled = true

[git_status]
disabled = true

[custom.jj]
when = "jj-starship detect"
shell = ["jj-starship"]
format = "$output "
